### PR TITLE
fix: maintain search when loading more

### PR DESCRIPTION
**Pull request by tenbradley**
## Context:
[DE44096](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F602251796719&fdp=true?fdp=true)
Searching in a learning path only worked the first time you search and the search can't be cleared. This seems to be fixed by something recently.
However, when loading more when searching, there are currently two other issues occurring with load more.
1. When loading more, the topic search for is used for the loaded topics.
2. Loading more always loads the same courses.

This pr addresses the first issue.

https://github.com/BrightspaceHypermediaComponents/foundation-engine/pull/115

## Quality:
Tested with locally built lms and bsi.

### CODE REVIEW

**Comment by tenbradley** [comment]
https://user-images.githubusercontent.com/69812595/130131568-9c0e765c-cf2d-4801-b921-55b359892f41.mp4

**Review by lloydwaddell — APPROVED** [review]
this looks good to me

**Review by Nidhi-github1994 — COMMENTED** [review]
Looks good.

**Review by zinabat — APPROVED** [review]
I have pulled this branch and the engine PR into a local BSI instance and it works as expected. Fix the tests and you're good to go

**Comment by tenbradley** [comment]
Hmm, reran tests and they passed this time. 🤔

**Pull request merged**
