### PR TITLE
fix: reduces content size and adds scroll bar

### PR DESCRIPTION
**Pull request by tenbradley**
### Context:
[DE42123](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F485899322752)
When dragging a list item to the top or bottom, the screen does not scroll.

### Quality:
Discussed design of added scrollbar with Abbie. Will look into a nicer scrollbar like what assignments uses.
Tested on polarislocalbsi in chrome.

### CODE REVIEW

**Comment by tenbradley** [comment]
newScrollbar

**Comment by tenbradley** [comment]
Scrolling in video form!
https://user-images.githubusercontent.com/69812595/105249235-c8859200-5b45-11eb-9d81-12ef88c1c228.mp4

**Comment by AKobets** [comment]
verified in Firefox, in both Desktop and Mobile simulation.

**Comment by AKobets** [comment]
Question: in future, it is planned to add additional settings vertical area on the right. How the scrolling will work then? Will it scroll  just name, description, list or also will scroll the settings area?

**Comment by tenbradley** [comment]
> Question: in future, it is planned to add additional settings vertical area on the right. How the scrolling will work then? Will it scroll just name, description, list or also will scroll the settings area?

When we add the sidebar, we will presumable move to using the primary-secondary template which is part of core and already has this scrollbar for the primary area.

**Review by AKobets — APPROVED** [review]

**Pull request merged**
